plugins {
    id 'java'
}

group = 'org.testing'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.1.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation("io.rest-assured:rest-assured:6.0.1")
    implementation("org.json:json:20260814")
    implementation("io.rest-assured:json-schema-validator:6.0.1")
    implementation("io.cucumber:cucumber-java:7.34.8")
    testImplementation("io.cucumber:cucumber-junit-platform-engine:7.34.8")
    testImplementation("org.projectlombok:lombok:1.18.48")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.48")
}

test {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed", "standardOut", "standardError"
    }
}